version: '3'
services:
  web:
    container_name: personal-website1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - /usr/share/nginx/html
    restart: always
    command: nginx -g 'daemon off;'
